User/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = "User"

urlpatterns = [
    path("",views.CreatePost,name="create_post"),
    path("register/",views.register,name="register"),
    path("login/",views.loginPage,name="login"),
    path("logout/",views.logout,name="logout"),
]

tradexa2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("User.urls")),
]

Product/models.py
from django.db import models

# Create your models here.

class ProductModel(models.Model):
    name = models.CharField(verbose_name="Name:",max_length=60)
    weight = models.FloatField(verbose_name="Weight With Kg:")
    price = models.FloatField(verbose_name="Price:")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

User/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class PostModel(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    text = models.TextField(verbose_name="Context of post:")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "Post"

User/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from django.forms import fields, widgets
from django.forms.forms import Form
from django.contrib.auth.models import User
from . import models


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'fields'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'fields'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'fields'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'fields'}))
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={'class':'passfields'})
    )

    password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(attrs={'class':'passfields'})
    )
    
    class Meta:
        model = User
        fields = ["first_name","last_name","email","username","password1","password2"]


class LoginForm(forms.Form):
    username = forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'fields'}))
    password = forms.CharField(required=True,widget=forms.PasswordInput(attrs={'class':'fields'}))


class PostForm(forms.ModelForm):
    class Meta:
        model = models.PostModel
        fields = ["text",]

Product/views.py
from django.shortcuts import render

# Create your views here.

User/views.py
from django.db import models
from django.db.models import fields
from django.shortcuts import redirect, render
from django.views.generic.edit import CreateView
from django.contrib.auth.models import User
from . import models
from . import forms
from django.contrib.auth import authenticate,login
from django.core.exceptions import ValidationError
from django.contrib.auth import logout as django_logout


# Create your views here.

# class CreatePost(CreateView):
#     model = models.PostModel
#     fields = ['text']
#     template_name = "add.html"
#     success_url = ""

#     def form_valid(self, form):
#         self.object = form.save(commit=False)
#         self.object.user = self.request.user
#         self.object.save()
#         return redirect("User:create_post")


def CreatePost(request):
    form = forms.PostForm()
    posts = models.PostModel.objects.all().using('users_posts_db')

    if request.method == "POST":
        form = forms.PostForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return redirect("User:create_post")

    context = {
        "form":form,
        "posts":posts
    }
    return render(request,"add.html",context)

# class RegisterView(CreateView):
#     model = User
#     fields = ["first_name","last_name","email","username","password"]
#     template_name = "register.html"
#     success_url = "User:login"

#     def form_valid(self, form):
#         self.object = form.save(commit=False)
#         self.object.save()
#         return redirect("User:login")


def logout(request):
    django_logout(request)
    return redirect("User:create_post")


def register(request):
    form = forms.RegisterForm()
    if request.method == "POST":
        form = forms.RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("User:login")

    context = {
    "form":form
    }
    return render(request,"register.html",context)

def loginPage(request):
    form = forms.LoginForm()
    if request.method == "POST":
        form = forms.LoginForm(request.POST)
        username = request.POST.get("username")
        password = request.POST.get("password")
        
        account = authenticate(request,username=username,password=password)
        if account is None:
            raise ValidationError(request,"Username or Password is false")
        else:
            login(request,account)
            return redirect("User:create_post")

    context = {
        "form":form
    }
    return render(request,"login.html",context)

templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load crispy_forms_tags %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Document</title>
</head>

{% include "include/navbar.html" %}

<body>
    <div class="container">
        {% if request.user.is_authenticated %}
            <form action=""  method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="create post" class="btn btn-info">
                <br><br>
            </form> 

        {% else %}
            You Are Not Autchanticated Please Login Or Register To Add Post
        {% endif %}

        {% for post in posts %}
            <div class="card" >
                <div class="card-body">
                    <h6 class="card-subtitle mb-2 text-muted">Writer: {{post.user}}</h6>
                    <p class="card-text">{{post.text}}</p>
                </div>
            </div>
            <hr>
        {% endfor %}

    </div>
    
</body>




    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</html>

templates/include/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      {% if request.user.is_authenticated %}
          <a class="nav-item nav-link active" href="{% url 'User:logout' %}">Logout</a>
          <span class="nav-item nav-link active">Hello! {{request.user}}</span>

      {% else %}
          <a class="nav-item nav-link active" href="{% url 'User:register' %}">Register <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link active" href="{% url 'User:login' %}">Login</a>
      {% endif %}
      
    </div>
  </div>
</nav>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load crispy_forms_tags %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Document</title>
</head>

{% include "include/navbar.html" %}

<body>
    <form action="" method="post" style="margin: 20px;">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Login" class="btn btn-primary">
    </form> 
        
</body>




    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load crispy_forms_tags %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Document</title>
</head>

{% include "include/navbar.html" %}

<body>
     <form action="" method="post" style="margin: 20px;">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Register" class="btn btn-primary">
    </form> 


</body>




    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</html>